spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.xjtutjc.blog: info
  file:
    path: log/blog-pro.log
    name: blog.%d{yyyy-MM-dd}.%i
    max-size: 100MB
server:
  port: 8081